language: objective-c
osx_image: xcode7
xcode-project: HMObjcSugar.xcodeproj
xcode_scheme: HMObjcSugar
script: 
  - xctool -project HMObjcSugar.xcodeproj -scheme HMObjcSugar build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)

